# docker-compose.yml

version: "3"

services:
  repl1:
    image: simagix/mongo-repl:3.6
    hostname: repl1
    volumes:
      - $HOME/ws/data/repl1:/data/db/
    command: /entrypoint.sh replset repl1 27017
    restart: unless-stopped
    networks:
      - mongo_net

  repl2:
    image: simagix/mongo-repl:3.6
    hostname: repl2
    volumes:
      - $HOME/ws/data/repl2:/data/db/
    command: /entrypoint.sh replset repl1 27017
    restart: unless-stopped
    networks:
      - mongo_net

  repl3:
    image: simagix/mongo-repl:3.6
    hostname: repl3
    volumes:
      - $HOME/ws/data/repl3:/data/db/
    command: /entrypoint.sh replset repl1 27017
    restart: unless-stopped
    networks:
      - mongo_net

  app1:
    image: simagix/mongo-repl:3.6
    hostname: app1
    command: /test.sh mongodb://admin:secret@repl1:27017,repl2:27017,repl3:27017/test?authSource=admin&replicaSet=replset
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge
