FROM centos:7
MAINTAINER Ken Chen <simagix@gmail.com>

RUN yum install -y krb5-libs krb5-auth-dialog krb5-workstation
ADD krb5.conf /etc/krb5.conf
ADD mongo/mongodb-enterprise.repo /etc/yum.repos.d/
RUN yum -y install mongodb-enterprise && \
    yum clean all && \
    mkdir -p /data/db && \
    chown -R mongod:mongod /data/db
RUN yum install -y openldap-clients nss-pam-ldapd
EXPOSE 27017

ADD certs/ca.crt /ca.crt
ADD certs/client.pem /client.pem
ADD certs/ldap.simagix.com.pem /server.pem
ADD certs/mongo.simagix.com.pem /mongo.pem
ADD mongo/mongod.conf /etc/mongod.conf
ADD entrypoint-mdb.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
