# Copyright 2019 Kuei-chun Chen. All rights reserved.
version: "3"

services:
  kerberos.simagix.com:
    image: simagix/kerberos
    hostname: kerberos.simagix.com
    environment:
      REALM: "SIMAGIX.COM"
      DOMAIN_REALM: "kerberos.simagix.com"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "secret"
    volumes:
      - /tmp/kerberos:/var/log/kerberos
    restart: unless-stopped

  ldap.simagix.com:
    image: simagix/openldap
    hostname: ldap.simagix.com
    environment:
      ADMIN_PASSWORD: "secret"
    restart: unless-stopped

  mongo.simagix.com:
    image: simagix/mongo-kerberos
    hostname: mongo.simagix.com
    depends_on:
      - kerberos.simagix.com
      - ldap.simagix.com
    ports:
      - 27017:27017
    environment:
      REALM: SIMAGIX.COM
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "secret"
    restart: unless-stopped
networks:
  kerberos_net:
    driver: bridge
